repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
  - repo: local
    hooks:
      - id: go-vet
        language: 'script'
        name: 'go-vet'
        entry: go-vet.sh
  - repo: local
    hooks:
      - id: staticcheck
        language: 'script'
        name: 'staticcheck'
        entry: staticcheck.sh
