version: "3.7"

services:
  redis:
    image: redis:5.0.6-alpine
    command: redis-server --requirepass password
    ports:
      - 6379:6379

  rds:
    image: mariadb:10.4.8-bionic
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    stop_grace_period: 1m30s
    labels:
      - "description=Maria DB Relational DB"

  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - ./sonic/sonic.cfg:/etc/sonic.cfg
      - sonic-data:/usr/src/sonic

  nsqlookupd:
#    network_mode: host
    image: nsqio/nsq:v1.2.0
    command: /nsqlookupd -broadcast-address nsqlookupd -http-address nsqlookupd:4161 -tcp-address nsqlookupd:4160
    ports:
      - "4160:4160" # TCP
      - "4161:4161" # HTTP

  nsqd:
#    network_mode: host
    image: nsqio/nsq:v1.2.0
    command: /nsqd -mem-queue-size 10000 -lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=nsqd -data-path=/data
    volumes:
      - nsq-data:/data
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
#    network_mode: host
    image: nsqio/nsq:v1.2.0
    command: /nsqadmin -lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

volumes:
  rds-data:
  sonic-data:
  nsq-data:
