version: "3.7"

services:
  redis:
    image: redis:5.0.6-alpine
    command: redis-server --requirepass password
    ports:
      - 6379:6379

  rds:
    image: mariadb:10.4.8-bionic
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    stop_grace_period: 1m30s
    labels:
      - "description=Maria DB Relational DB"

  search:
    image: benjaminslabbert/trak_search:1.0.4-2019-10-24
    ports:
      - 50052
    environment:
      - SONIC_HOST=sonic
      - SONIC_PORT=1491
      - SONIC_PASSWORD=password
      - SONIC_POOL_SIZE=2
      - SONIC_TIMEOUT_CONN=5000
      - SONIC_TIMEOUT_READ=5000
      - JAVA_OPTS=-Xmx64m -Xms64m -XX:+TieredCompilation -Xss256k -Xverify:none -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+CMSClassUnloadingEnabled -XshowSettings:vm -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -XX:+HeapDumpOnOutOfMemoryError -noverify
    depends_on:
      - redis
    labels:
      - "description=Trak Search, searches on Sonic"
    stop_grace_period: 1m30s
    restart: on-failure

  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - ./sonic/sonic.cfg:/etc/sonic.cfg
      - sonic-data:/usr/src/sonic

  # todo need to connect to nsqlookupd, see: https://stackoverflow.com/questions/48536963/nsq-cannot-consume-message-by-connecting-to-nsqlookupd
  nsqlookupd:
    network_mode: host
    image: nsqio/nsq:v1.1.0
    command: /nsqlookupd
    ports:
      - "4160:4160" # TCP
      - "4161:4161" # HTTP

  nsqd:
    network_mode: host
    image: nsqio/nsq:v1.1.0
    command: /nsqd -lookupd-tcp-address=127.0.0.1:4160 -broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    network_mode: host
    image: nsqio/nsq:v1.1.0
    command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

volumes:
  rds-data:
  sonic-data:
